# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

services:

  peer5:
    image: hyperledger/fabric-peer${PEER5_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer5
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer4:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer5:7051
      - CORE_PEER_MSPCONFIGPATH=${PEER5_CORE_PEER_MSPCONFIGPATH}
      - CORE_PEER_LOCALMSPID=${PEER5_CORE_PEER_LOCALMSPID}
      - CORE_PEER_TLS_CERT_FILE=${PEER5_CORE_PEER_TLS_CERT_FILE}
      - CORE_PEER_TLS_KEY_FILE=${PEER5_CORE_PEER_TLS_KEY_FILE}
      - CORE_PEER_TLS_ROOTCERT_FILE=${PEER5_CORE_PEER_TLS_ROOTCERT_FILE}
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER5_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
      - CORE_PEER_FILESYSTEMPATH=${PEER5_CORE_PEER_FILESYSTEMPATH}
    depends_on:
      - orderer0

  peer6:
    image: hyperledger/fabric-peer${PEER6_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer6
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer7:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer6:7051
      - CORE_PEER_MSPCONFIGPATH=${PEER6_CORE_PEER_MSPCONFIGPATH}
      - CORE_PEER_LOCALMSPID=${PEER6_CORE_PEER_LOCALMSPID}
      - CORE_PEER_TLS_CERT_FILE=${PEER6_CORE_PEER_TLS_CERT_FILE}
      - CORE_PEER_TLS_KEY_FILE=${PEER6_CORE_PEER_TLS_KEY_FILE}
      - CORE_PEER_TLS_ROOTCERT_FILE=${PEER6_CORE_PEER_TLS_ROOTCERT_FILE}
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER6_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
      - CORE_PEER_FILESYSTEMPATH=${PEER6_CORE_PEER_FILESYSTEMPATH}
    depends_on:
      - orderer0

  peer7:
    image: hyperledger/fabric-peer${PEER7_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer7
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer6:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer7:7051
      - CORE_PEER_MSPCONFIGPATH=${PEER7_CORE_PEER_MSPCONFIGPATH}
      - CORE_PEER_LOCALMSPID=${PEER7_CORE_PEER_LOCALMSPID}
      - CORE_PEER_TLS_CERT_FILE=${PEER7_CORE_PEER_TLS_CERT_FILE}
      - CORE_PEER_TLS_KEY_FILE=${PEER7_CORE_PEER_TLS_KEY_FILE}
      - CORE_PEER_TLS_ROOTCERT_FILE=${PEER7_CORE_PEER_TLS_ROOTCERT_FILE}
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER7_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
      - CORE_PEER_FILESYSTEMPATH=${PEER7_CORE_PEER_FILESYSTEMPATH}
    depends_on:
      - orderer0

