# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0:
    hostname: orderer0
    image: hyperledger/fabric-orderer${ORDERER0_VERSION_EXTENSION}
    extends:
      file: dc-orderer-base.yml
      service: orderer
    environment:
    - ORDERER_GENERAL_LOCALMSPDIR=${ORDERER0_ORDERER_GENERAL_LOCALMSPDIR}
    - ORDERER_GENERAL_LOCALMSPID=${ORDERER0_ORDERER_GENERAL_LOCALMSPID}
    - ORDERER_GENERAL_TLS_PRIVATEKEY=${ORDERER0_ORDERER_GENERAL_TLS_PRIVATEKEY}
    - ORDERER_GENERAL_TLS_CERTIFICATE=${ORDERER0_ORDERER_GENERAL_TLS_CERTIFICATE}
    - ORDERER_GENERAL_TLS_ROOTCAS=${ORDERER0_ORDERER_GENERAL_TLS_ROOTCAS}
    - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=${ORDERER0_ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY}
    - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=${ORDERER0_ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE}
    - ORDERER_FILELEDGER_LOCATION=${ORDERER0_ORDERER_FILELEDGER_LOCATION}
    - ORDERER_CONSENSUS_WALDIR=${ORDERER0_ORDERER_CONSENSUS_WALDIR}
    - ORDERER_CONSENSUS_SNAPDIR=${ORDERER0_ORDERER_CONSENSUS_SNAPDIR}


  orderer1:
    hostname: orderer1
    image: hyperledger/fabric-orderer${ORDERER1_VERSION_EXTENSION}
    extends:
      service: orderer0
    environment:
      - ORDERER_GENERAL_LOCALMSPID=${ORDERER1_ORDERER_GENERAL_LOCALMSPID}
      - ORDERER_GENERAL_LOCALMSPDIR=${ORDERER1_ORDERER_GENERAL_LOCALMSPDIR}
      - ORDERER_GENERAL_TLS_PRIVATEKEY=${ORDERER1_ORDERER_GENERAL_TLS_PRIVATEKEY}
      - ORDERER_GENERAL_TLS_CERTIFICATE=${ORDERER1_ORDERER_GENERAL_TLS_CERTIFICATE}
      - ORDERER_GENERAL_TLS_ROOTCAS=${ORDERER1_ORDERER_GENERAL_TLS_ROOTCAS}
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=${ORDERER1_ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY}
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=${ORDERER1_ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE}
      - ORDERER_FILELEDGER_LOCATION=${ORDERER1_ORDERER_FILELEDGER_LOCATION}
      - ORDERER_CONSENSUS_WALDIR=${ORDERER1_ORDERER_CONSENSUS_WALDIR}
      - ORDERER_CONSENSUS_SNAPDIR=${ORDERER1_ORDERER_CONSENSUS_SNAPDIR}

  orderer2:
    hostname: orderer2
    image: hyperledger/fabric-orderer${ORDERER2_VERSION_EXTENSION}
    extends:
      service: orderer0
    environment:
      - ORDERER_GENERAL_LOCALMSPID=${ORDERER2_ORDERER_GENERAL_LOCALMSPID}
      - ORDERER_GENERAL_LOCALMSPDIR=${ORDERER2_ORDERER_GENERAL_LOCALMSPDIR}
      - ORDERER_GENERAL_TLS_PRIVATEKEY=${ORDERER2_ORDERER_GENERAL_TLS_PRIVATEKEY}
      - ORDERER_GENERAL_TLS_CERTIFICATE=${ORDERER2_ORDERER_GENERAL_TLS_CERTIFICATE}
      - ORDERER_GENERAL_TLS_ROOTCAS=${ORDERER2_ORDERER_GENERAL_TLS_ROOTCAS}
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=${ORDERER2_ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY}
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=${ORDERER2_ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE}
      - ORDERER_FILELEDGER_LOCATION=${ORDERER2_ORDERER_FILELEDGER_LOCATION}
      - ORDERER_CONSENSUS_WALDIR=${ORDERER2_ORDERER_CONSENSUS_WALDIR}
      - ORDERER_CONSENSUS_SNAPDIR=${ORDERER2_ORDERER_CONSENSUS_SNAPDIR}
    depends_on:
    - orderer0
    - orderer1

  peer0:
    image: hyperledger/fabric-peer${PEER0_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
    - CORE_PEER_ID=vp0
#    - CORE_PEER_GOSSIP_BOOTSTRAP=peer1:7051
    - CORE_PEER_GOSSIP_ENDPOINT=peer0:7051
    - CORE_PEER_PROFILE_ENABLED=true
    - CORE_PEER_MSPCONFIGPATH=${PEER0_CORE_PEER_MSPCONFIGPATH}
    - CORE_PEER_LOCALMSPID=${PEER0_CORE_PEER_LOCALMSPID}
    - CORE_PEER_TLS_CERT_FILE=${PEER0_CORE_PEER_TLS_CERT_FILE}
    - CORE_PEER_TLS_KEY_FILE=${PEER0_CORE_PEER_TLS_KEY_FILE}
    - CORE_PEER_TLS_ROOTCERT_FILE=${PEER0_CORE_PEER_TLS_ROOTCERT_FILE}
    - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER0_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
    - CORE_PEER_FILESYSTEMPATH=${PEER0_CORE_PEER_FILESYSTEMPATH}
    depends_on:
    - orderer0
      #ports:
    #- 7050:6060

  peer1:
    image: hyperledger/fabric-peer${PEER1_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
    - CORE_PEER_ID=vp1
#    - CORE_PEER_GOSSIP_BOOTSTRAP=peer0:7051
    - CORE_PEER_GOSSIP_ENDPOINT=peer1:7051
    - CORE_PEER_MSPCONFIGPATH=${PEER1_CORE_PEER_MSPCONFIGPATH}
    - CORE_PEER_LOCALMSPID=${PEER1_CORE_PEER_LOCALMSPID}
    - CORE_PEER_TLS_CERT_FILE=${PEER1_CORE_PEER_TLS_CERT_FILE}
    - CORE_PEER_TLS_KEY_FILE=${PEER1_CORE_PEER_TLS_KEY_FILE}
    - CORE_PEER_TLS_ROOTCERT_FILE=${PEER1_CORE_PEER_TLS_ROOTCERT_FILE}
    - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER1_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
    - CORE_PEER_FILESYSTEMPATH=${PEER1_CORE_PEER_FILESYSTEMPATH}
    depends_on:
    - orderer0

  peer2:
    image: hyperledger/fabric-peer${PEER2_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
    - CORE_PEER_ID=vp2
#    - CORE_PEER_GOSSIP_BOOTSTRAP=peer3:7051
    - CORE_PEER_GOSSIP_ENDPOINT=peer2:7051
    - CORE_PEER_MSPCONFIGPATH=${PEER2_CORE_PEER_MSPCONFIGPATH}
    - CORE_PEER_LOCALMSPID=${PEER2_CORE_PEER_LOCALMSPID}
    - CORE_PEER_TLS_CERT_FILE=${PEER2_CORE_PEER_TLS_CERT_FILE}
    - CORE_PEER_TLS_KEY_FILE=${PEER2_CORE_PEER_TLS_KEY_FILE}
    - CORE_PEER_TLS_ROOTCERT_FILE=${PEER2_CORE_PEER_TLS_ROOTCERT_FILE}
    - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER2_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
    - CORE_PEER_FILESYSTEMPATH=${PEER2_CORE_PEER_FILESYSTEMPATH}
    depends_on:
    - orderer0

  peer3:
    image: hyperledger/fabric-peer${PEER3_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
    - CORE_PEER_ID=vp3
#    - CORE_PEER_GOSSIP_BOOTSTRAP=peer2:7051
    - CORE_PEER_GOSSIP_ENDPOINT=peer3:7051
    - CORE_PEER_MSPCONFIGPATH=${PEER3_CORE_PEER_MSPCONFIGPATH}
    - CORE_PEER_LOCALMSPID=${PEER3_CORE_PEER_LOCALMSPID}
    - CORE_PEER_TLS_CERT_FILE=${PEER3_CORE_PEER_TLS_CERT_FILE}
    - CORE_PEER_TLS_KEY_FILE=${PEER3_CORE_PEER_TLS_KEY_FILE}
    - CORE_PEER_TLS_ROOTCERT_FILE=${PEER3_CORE_PEER_TLS_ROOTCERT_FILE}
    - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER3_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
    - CORE_PEER_FILESYSTEMPATH=${PEER3_CORE_PEER_FILESYSTEMPATH}
    depends_on:
    - orderer0

  peer4:
    image: hyperledger/fabric-peer${PEER4_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
    - CORE_PEER_ID=vp4
    #      - CORE_PEER_GOSSIP_BOOTSTRAP=peer2:7051
    - CORE_PEER_GOSSIP_ENDPOINT=peer4:7051
    - CORE_PEER_MSPCONFIGPATH=${PEER4_CORE_PEER_MSPCONFIGPATH}
    - CORE_PEER_LOCALMSPID=${PEER4_CORE_PEER_LOCALMSPID}
    - CORE_PEER_TLS_CERT_FILE=${PEER4_CORE_PEER_TLS_CERT_FILE}
    - CORE_PEER_TLS_KEY_FILE=${PEER4_CORE_PEER_TLS_KEY_FILE}
    - CORE_PEER_TLS_ROOTCERT_FILE=${PEER4_CORE_PEER_TLS_ROOTCERT_FILE}
    - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER4_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
    - CORE_PEER_FILESYSTEMPATH=${PEER4_CORE_PEER_FILESYSTEMPATH}
    depends_on:
    - orderer0


  peer5:
    image: hyperledger/fabric-peer${PEER5_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer5
      #    - CORE_PEER_GOSSIP_BOOTSTRAP=peer4:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer5:7051
      - CORE_PEER_MSPCONFIGPATH=${PEER5_CORE_PEER_MSPCONFIGPATH}
      - CORE_PEER_LOCALMSPID=${PEER5_CORE_PEER_LOCALMSPID}
      - CORE_PEER_TLS_CERT_FILE=${PEER5_CORE_PEER_TLS_CERT_FILE}
      - CORE_PEER_TLS_KEY_FILE=${PEER5_CORE_PEER_TLS_KEY_FILE}
      - CORE_PEER_TLS_ROOTCERT_FILE=${PEER5_CORE_PEER_TLS_ROOTCERT_FILE}
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER5_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
      - CORE_PEER_FILESYSTEMPATH=${PEER5_CORE_PEER_FILESYSTEMPATH}
    depends_on:
      - orderer0

  peer6:
    image: hyperledger/fabric-peer${PEER6_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer6
      #    - CORE_PEER_GOSSIP_BOOTSTRAP=peer7:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer6:7051
      - CORE_PEER_MSPCONFIGPATH=${PEER6_CORE_PEER_MSPCONFIGPATH}
      - CORE_PEER_LOCALMSPID=${PEER6_CORE_PEER_LOCALMSPID}
      - CORE_PEER_TLS_CERT_FILE=${PEER6_CORE_PEER_TLS_CERT_FILE}
      - CORE_PEER_TLS_KEY_FILE=${PEER6_CORE_PEER_TLS_KEY_FILE}
      - CORE_PEER_TLS_ROOTCERT_FILE=${PEER6_CORE_PEER_TLS_ROOTCERT_FILE}
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER6_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
      - CORE_PEER_FILESYSTEMPATH=${PEER6_CORE_PEER_FILESYSTEMPATH}
    depends_on:
      - orderer0

  peer7:
    image: hyperledger/fabric-peer${PEER7_VERSION_EXTENSION}
    extends:
      file: dc-peer-base.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer7
      #    - CORE_PEER_GOSSIP_BOOTSTRAP=peer6:7051
      - CORE_PEER_GOSSIP_ENDPOINT=peer7:7051
      - CORE_PEER_MSPCONFIGPATH=${PEER7_CORE_PEER_MSPCONFIGPATH}
      - CORE_PEER_LOCALMSPID=${PEER7_CORE_PEER_LOCALMSPID}
      - CORE_PEER_TLS_CERT_FILE=${PEER7_CORE_PEER_TLS_CERT_FILE}
      - CORE_PEER_TLS_KEY_FILE=${PEER7_CORE_PEER_TLS_KEY_FILE}
      - CORE_PEER_TLS_ROOTCERT_FILE=${PEER7_CORE_PEER_TLS_ROOTCERT_FILE}
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=${PEER7_CORE_PEER_TLS_SERVERHOSTOVERRIDE}
      - CORE_PEER_FILESYSTEMPATH=${PEER7_CORE_PEER_FILESYSTEMPATH}
    depends_on:
      - orderer0
