# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peer/lifecycle/chaincode_definition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='peer/lifecycle/chaincode_definition.proto',
  package='lifecycle',
  syntax='proto3',
  serialized_pb=_b('\n)peer/lifecycle/chaincode_definition.proto\x12\tlifecycle\"^\n\x18\x43haincodeEndorsementInfo\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x15\n\rinit_required\x18\x02 \x01(\x08\x12\x1a\n\x12\x65ndorsement_plugin\x18\x03 \x01(\t\"R\n\x17\x43haincodeValidationInfo\x12\x19\n\x11validation_plugin\x18\x01 \x01(\t\x12\x1c\n\x14validation_parameter\x18\x02 \x01(\x0c\x42\x66\n,org.hyperledger.fabric.protos.peer.lifecycleZ6github.com/hyperledger/fabric-protos-go/peer/lifecycleb\x06proto3')
)




_CHAINCODEENDORSEMENTINFO = _descriptor.Descriptor(
  name='ChaincodeEndorsementInfo',
  full_name='lifecycle.ChaincodeEndorsementInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='lifecycle.ChaincodeEndorsementInfo.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='init_required', full_name='lifecycle.ChaincodeEndorsementInfo.init_required', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endorsement_plugin', full_name='lifecycle.ChaincodeEndorsementInfo.endorsement_plugin', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=150,
)


_CHAINCODEVALIDATIONINFO = _descriptor.Descriptor(
  name='ChaincodeValidationInfo',
  full_name='lifecycle.ChaincodeValidationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='validation_plugin', full_name='lifecycle.ChaincodeValidationInfo.validation_plugin', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='validation_parameter', full_name='lifecycle.ChaincodeValidationInfo.validation_parameter', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=234,
)

DESCRIPTOR.message_types_by_name['ChaincodeEndorsementInfo'] = _CHAINCODEENDORSEMENTINFO
DESCRIPTOR.message_types_by_name['ChaincodeValidationInfo'] = _CHAINCODEVALIDATIONINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChaincodeEndorsementInfo = _reflection.GeneratedProtocolMessageType('ChaincodeEndorsementInfo', (_message.Message,), dict(
  DESCRIPTOR = _CHAINCODEENDORSEMENTINFO,
  __module__ = 'peer.lifecycle.chaincode_definition_pb2'
  # @@protoc_insertion_point(class_scope:lifecycle.ChaincodeEndorsementInfo)
  ))
_sym_db.RegisterMessage(ChaincodeEndorsementInfo)

ChaincodeValidationInfo = _reflection.GeneratedProtocolMessageType('ChaincodeValidationInfo', (_message.Message,), dict(
  DESCRIPTOR = _CHAINCODEVALIDATIONINFO,
  __module__ = 'peer.lifecycle.chaincode_definition_pb2'
  # @@protoc_insertion_point(class_scope:lifecycle.ChaincodeValidationInfo)
  ))
_sym_db.RegisterMessage(ChaincodeValidationInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n,org.hyperledger.fabric.protos.peer.lifecycleZ6github.com/hyperledger/fabric-protos-go/peer/lifecycle'))
# @@protoc_insertion_point(module_scope)
